---
- name: Fetch kubeconfig from remote system
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  no_log: true
  register: slurped_kubeconfig

- name: Build kubeconfig that points to the Subject Altname
  ansible.builtin.set_fact:
    k3s_kubeconfig: >-
      {{
        content | combine({
          'clusters': [
            {
              'name': cluster_name,
              'cluster': {
                'server': kubeapi_url,
                'certificate-authority-data': certificate_authority
              }
            }
          ]
        })
      }}
  no_log: true
  vars:
    kubeapi_url: "https://{{ k3s_tls_san }}:6443"
    cluster_name: "{{ content.clusters[0].name }}"
    certificate_authority: "{{ content.clusters[0].cluster['certificate-authority-data'] }}"
    content: "{{ slurped_kubeconfig['content'] | b64decode | from_yaml }}"

- name: Create local kubeconfig path
  delegate_to: localhost
  ansible.builtin.file:
    path: "~{{ local_user_id }}/.kube"
    owner: "{{ local_user_id }}"
    mode: "0700"
    state: directory
  vars:
    local_user_id: "{{ lookup('ansible.builtin.env', 'USER') }}"

- name: Write out local kubeconfig
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ k3s_kubeconfig | to_nice_yaml }}"
    dest: "~{{ local_user_id }}/.kube/config"
    owner: "{{ local_user_id }}"
    mode: "0600"
  no_log: true
  vars:
    local_user_id: "{{ lookup('ansible.builtin.env', 'USER') }}"
